app/shop/urls.py
from django.urls import path, include

from .views import view, shop, cart, order, blog, cdek, error, pmap

app_name = 'shop'

handler404 = 'shop.views.error.page_not_found'
handler400 = 'shop.views.error.bad_request'
handler403 = 'shop.views.error.permission_denied'

urlpatterns = [
    path('', view.home, name='home'),
    path('make/map/', pmap.make_map, name='make_map'),
    path('about-us/', view.about, name='about'),
    path(u'доставка-и-оплата/', view.shipping_payment, name='shipping_payment'),
    path('pdd/', view.pdd, name='pdd'),
    path('video/', view.video_list, name='video_list'),
    path('policy/', view.policy, name='policy'),
    path('clear/session/', view.clear_session, name='clear_session'),
    path('contact/', include([
        path('', view.contact, name='contact'),
        path('form/', view.get_message_form, name='get_message_form'),
        path('<str:message>/', view.contact, name='contact'),
        path('send/massage/', view.contact_send_message, name='contact_send_message'),
    ])),
    path('shop/', shop.product_list, name='shop_page'),
    path('product/loop_id/', shop.loop_id, name='loop_id'),
    path('product/<slug:slug>/', shop.product_detail, name='product_detail'),
    # /product-category/{{brand}}/ - прописан жестко в product/list.html - 1 раз
    path(u'product-category/', include([
        path('аксессуары/', shop.product_list, name='product_list'),
        path('filter/', shop.product_filter, name='product_filter'),
        path('size/<int:size>/', shop.product_list_size, name='product_list_size'),
        path('sort/<str:sort_by>/', shop.product_sort_by, name='product_sort_by'),
        path('toggle/<str:view_style>/', shop.toggle_style, name='toggle_style'),
        path('<slug:category_slug>/', shop.product_list, name='product_list_by_category'),
        path('krepleniya-isofix/<slug:category_slug>/',
             shop.product_list, name='product_list_by_category'),
    ])),
    path('cart/', include([
        path('', cart.cart_detail, name='cart_detail'),
        path('remove/loop/marker/', cart.remove_loop_marker, name='remove_loop_marker'),
        path('json/', cart.cart_json, name='cart_json'),
        path('clear/', cart.cart_clear, name='cart_clear'),
        path('count/quantity/on/', cart.cart_count_quantity, name='cart_count_quantity'),
        path('add/<int:product_id>/', cart.cart_add, name='cart_add'),
        # /cart/remove/id - прописан жестко в JS
        path('remove/<int:product_id>/', cart.cart_remove, name='cart_remove'),
        # /cart/remove/loop/id - прописан жестко в JS
        path('remove/loop/<int:product_id>/', cart.cart_remove_loop, name='cart_remove_loop'),
        path('add/delivery/tax/', cart.add_delivery_tax, name='add_delivery_tax'),
        path('add/percent/', cart.add_percent, name='add_percent'),
        # del/sessionkeyloop/<int:product_id>/ - прописан жестко в JS
        path('del/sessionkeyloop/<int:product_id>/',
             cart.cart_loop_off, name='cart_loop_off'),
        path('set/marker/on/<int:product_id>/',
             cart.set_loop_marker_on, name='set_loop_marker_on'),
    ])),
    path('order/', include([
        path('create/', order.order_create, name='order_create'),
        path('created/', order.order_created, name='order_created'),
    ])),
    path('blog/', include([
        path('', blog.post_list, name='post_list'),
        path('<slug:post>/', blog.post_detail, name='post_detail'),
    ])),
    path('cdek/', include([
        path('tariffs/', cdek.tarifflist, name='tarifflist'),
        path('city/', cdek.get_city, name='get_city'),
        path('cities/', cdek.get_cities, name='get_cities'),
    ])),
    path('404/', error.page_not_found),
    path('400/', error.bad_request),
    path('403/', error.permission_denied),
    # re_path(r'^\w*', view.ret_index, name='ret_index'),
    # path('order/', include([])),
]

app/shop/views/blog.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage,\
                                  PageNotAnInteger
from django.views.generic import ListView
from django.views.decorators.cache import cache_page
from ..models import Post, Product
from .. import POSTS_DETAIL_CACHE_TIME
'''
https://isofix-msk.ru/blog/instrukciya-isofix/
https://isofix-msk.ru/blog/neskolko-kresel/
https://isofix-msk.ru/blog/podushka-bezopasnosti/
https://isofix-msk.ru/blog/avto-s-isofix/
https://isofix-msk.ru/blog/sertificati-kresel/
https://isofix-msk.ru/blog/isofix-standart/
'''

def post_list(request):
    object_list = Post.published.all()
    paginator = Paginator(object_list, 12)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request,
                 'shop/post/list.html',
                 {'page': posts,
                  'posts': posts})

# @cache_page(POSTS_DETAIL_CACHE_TIME)
def post_detail(request, post):
    post = get_object_or_404(Post, slug=post, status='published')
    return render(request,
                  'shop/post/detail.html',
            {
                  'post': post,
            })


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'shop/post/list.html'

app/shop/views/cart.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.http import HttpResponse
from decimal import Decimal

from .. import CART_SESSION_ID, NO_IMAGE_PATH, PERCENT
from ..models import Product
from ..cart import Cart
from ..ctx_proc import currency

import json
import logging


@require_POST
def cart_add(request, product_id):
    try:
        quantity = int(request.POST.get('quantity'))
        override = int(request.POST.get('override'))
        install = int(request.POST.get('price_install') or 0)
        loop = request.POST.get('loop')
    except Exception as e:
        print(e)
    else:
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)

        if quantity > 0:
            cart.add(product=product,
                     quantity=quantity,
                     override_quantity=override,
                     install=install,
                     loop=loop)

            if request.headers.get('X-Requested-With'):
                price = Decimal(cart.cart[str(product_id)]['price']) * quantity
                price_install = Decimal(cart.cart[str(product_id)]['price_install']) * quantity

                total_price = currency(request)['currency'] + str(price)
                total_price_install = currency(request)['currency'] + str(price_install)

                sub_total = currency(
                    request)['currency'] + str(cart.get_total_price())

                return HttpResponse(json.dumps({
                    'product_id': product_id,
                    'result': 'update',
                    'total_price': total_price,
                    'total_price_install': total_price_install,
                    'sub_total': sub_total,
                    'cart_length': len(cart),
                }))

    return redirect('shop:cart_detail')


@require_POST
def add_delivery_tax(request):
    delivery_tax = request.POST.get('delivery_tax')
    grand_total = 0
    cart = Cart(request)

    if delivery_tax:
        if int(delivery_tax) >= 0:
            grand_total = Decimal(cart.get_total_price()) + Decimal(delivery_tax)

            return HttpResponse(json.dumps({
                'grand_total': str(grand_total)
            }))

    return HttpResponse(json.dumps({'error': 'fail add delivery tax!'}))


@require_POST
def add_percent(request):
    percent = request.POST.get('percent')
    delivery_sum = request.POST.get('delivery_sum')
    grand_total = 0

    cart = Cart(request)

    if percent is not None:
        if int(percent) >= 0:
            percent = str(PERCENT) if int(percent) > 0 else '0'
            logging.debug('percent %s', percent)
            logging.debug('delivery_sum %s', delivery_sum)
            # percent = ((cart.get_total_price() + Decimal(delivery_sum)) /
            #            Decimal(100)) * Decimal(percent)
            # grand_total = (cart.get_total_price() + Decimal(delivery_sum)) + percent
            p = (cart.get_total_price() + Decimal(delivery_sum)) * Decimal(percent) / Decimal(100)
            grand_total = (cart.get_total_price() + Decimal(delivery_sum)) + p

            return HttpResponse(json.dumps({
                'grand_total': str(grand_total)
            }))

    return HttpResponse(json.dumps({'error': 'no add percent!'}))


@require_POST
def set_loop_marker_on(request, product_id):
    if request.session[CART_SESSION_ID].get(str(product_id)):
        request.session[CART_SESSION_ID][str(product_id)]['loop'] = 'on'
        request.session.modified = True
        return HttpResponse(f'set marker for product {product_id} OK')
    return HttpResponse(f'set marker for product {product_id} FAIL')


@require_POST
def remove_loop_marker(request):
    for item in request.session[CART_SESSION_ID].values():
        if 'loop' in item:
            item['loop'] = 'off'
    request.session.modified = True
    return HttpResponse('remove markers')


@require_POST
def cart_count_quantity(request):
    cart = Cart(request)
    quantity_on = 0
    for item in cart:
        if item.get('loop_quantity'):
            quantity_on += int(item['quantity'])

    return HttpResponse(json.dumps({'quantity_on': str(quantity_on)}))


@require_POST
def cart_loop_off(request, product_id):
    ''' удаляет отметку loop: on '''
    if request.session.get(CART_SESSION_ID):
        if request.session[CART_SESSION_ID][str(product_id)].get('loop'):
            del request.session[CART_SESSION_ID][str(product_id)]['loop']
            request.session.modified = True
            return HttpResponse(json.dumps({'loop_del': 'ok'}))

    return HttpResponse(json.dumps({'loop_del': 'no'}))


@require_POST
def cart_remove_loop(request, product_id):
    ''' колличество для установки петель якорного крепления '''
    logging.debug('cart_remove_loop %s', product_id)
    if request.session[CART_SESSION_ID].get(str(product_id)):
        qty = int(request.POST.get('quantity'))

        cart = Cart(request)
        # product only loop
        cart.session[CART_SESSION_ID][str(product_id)]['loop_quantity'] = 0
        cart.save()

        product = get_object_or_404(Product, attribute='loop')
        quantity = 0

        for item in cart.cart.values():
            if item.get('loop_quantity'):
                quantity += int(item['loop_quantity'])

        if quantity <= 0 and cart.session[CART_SESSION_ID].get(str(product.id)):
            del cart.session[CART_SESSION_ID][str(product.id)]
        else:
            if cart.session[CART_SESSION_ID].get(str(product.id)):
                cart.session[CART_SESSION_ID][str(product.id)]['quantity'] = quantity
        cart.save()

        return HttpResponse(json.dumps({"loop_quantity": quantity}))
    return HttpResponse(json.dumps({"loop_quantity": 'fail'}))


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)

    if (product.attribute == 'loop'):
        for item in cart.cart.values():
            if item.get('loop_quantity'):
                del item['loop_quantity']
        cart.save()

    if request.headers.get('X-Requested-With'):
        sub_total = currency(
            request)['currency'] + str(cart.get_total_price())
        return HttpResponse(json.dumps({
            'product_id': product_id,
            'result': 'remove',
            'sub_total': sub_total,
            'cart_length': len(cart),
        }))
    return redirect('shop:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'shop/cart/detail.html', {
        'cart': cart,
        'deactivate_mini_cart': True,
    })


def cart_json(request):
    cart = Cart(request)
    response_data = {}

    if len(cart) and request.headers.get('X-Requested-With'):
        for item in cart:
            product = item['product']
            image = NO_IMAGE_PATH
            if product.image_base:
                image = product.image_base.url
            response_data[str(product.id)] = {
                'name': product.name,
                'image': image,
                'price': currency(request)['currency'] + str(product.price),
                'total_price': currency(request)['currency'] + str(item['total_price']),
                'quantity': item['quantity'],
                'product_url': product.get_absolute_url(),
                'price_install': currency(request)['currency'] + str(item['price_install']),
                'attribute': product.attribute
            }
        response_data['sub_total'] = currency(
            request)['currency'] + str(cart.get_total_price())
        response_data['cart_length'] = str(len(cart))
        return HttpResponse(json.dumps(response_data))
    # else:
    #     return HttpResponse(json.dumps({'cart': 'empty'}))
    return redirect('shop:product_list')


def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect('shop:product_list')

app/shop/views/error.py
from django.shortcuts import render, redirect
from django.http import HttpResponse


def page_not_found(request, exception=None, template_name=''):
    return HttpResponse('404')


def bad_request(request, exception=None, template_name=''):
    return HttpResponse('400')


def permission_denied(request, exception=None, template_name=''):
    return HttpResponse('403')

app/shop/views/pmap.py
import os
import datetime
from django.views.decorators.http import require_POST
from django.http import HttpResponse
from urllib.parse import unquote
from pathlib import Path
from urllib.parse import unquote
from ..models import Category, Product


@require_POST
def make_map(request):
    cats = Category.objects.all()
    products = Product.objects.all()
    # host = request.META.get('HTTP_ORIGIN', 'https://isofix-msk.ru')
    host = 'https://isofix-msk.ru'
    base_dir = Path(__file__).resolve().parent.parent.parent
    file_path = os.path.join(base_dir, 'media', 'products', 'map.xml')
    dt = datetime.datetime.now()
    yml_catalog = '<yml_catalog date="' + dt.strftime('%Y-%m-%d %H:%M:%S') + '">\n'
    shop = '\t<shop>\n\t\t<name>ISOFIX-MSK</name>\n'

    categories = '\t\t<categories>\n'
    for cat in cats:
        categories += f'\t\t\t<category id="{cat.id}">\n\t\t\t\t<name>{cat.name}</name>\n\t\t\t</category>\n'
    categories += '\t\t</categories>\n'
    shop += categories

    offers = '\t\t<offers>\n'
    count = 0
    for p in products:
        offer = f'\t\t\t<offer id="{p.id}" productId="{p.id}" quantity="1">\n'
        offer += f'\t\t\t\t<categoryId>{p.category_id}</categoryId>\n'
        if p.image_base:
            offer += f'\t\t\t\t<picture>{host}{unquote(p.image_base.url)}</picture>\n'
        offer += f'\t\t\t\t<name>{p.name}</name>\n'
        offer += f'\t\t\t\t<productName>{p.name}</productName>\n'
        offer += f'\t\t\t\t<price>{p.price}</price>\n'
        offer += f'\t\t\t\t<url>{host}/product/{p.slug}/</url>\n'
        if p.brand_car:
            offer += f'\t\t\t\t<param code="pa_brand" name="Марка машины:">{p.brand_car}</param>\n'
        if p.year:
            offer += f'\t\t\t\t<param code="pa_god-vipuska" name="Год выпуска:">{p.year}</param>\n'
        if p.model_car:
            offer += f'\t\t\t\t<param code="pa_model" name="Модель машины:">{p.model_car}</param>\n'
        if p.seat_type:
            offer += f'\t\t\t\t<param code="pa_tip-sideniya" name="Тип сидения:">{p.seat_type}</param>\n'
        offer += f'\t\t\t\t<param code="article" name="Article">{p.item_number}</param>\n'
        # offer += '\t\t\t\t<dimensions>50/20/10</dimensions>\n'
        # offer += '\t\t\t\t<weight>1.5</weight>\n'
        # offer += '\t\t\t\t<vatRate>none</vatRate>\n'
        offer += '\t\t\t</offer>\n'
        offers += offer

    offers += '\t\t</offers>\n'
    shop += offers
    # offers
    shop += '\t</shop>\n'
    yml_catalog += shop
    yml_catalog += '</yml_catalog>'
    with open(file_path, mode='w', encoding='utf-8') as file:
        file.write(yml_catalog)
    return HttpResponse(file_path)

app/shop/templates/shop/includes/header.html
<header class="header-area">
    <div class="header-large-device section-padding-2">
        <div class="header-top header-top-ptb-3 bg-black">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-xl-4 col-lg-3">
                        <div class="header-quick-contect">
                            <ul>
                                <li>
                                    <i class="icon-phone "></i>
                                    <a class="text-white" href="tel:+79651116527">+7-965-111-65-27</a>
                                </li>
                                <li><i class="icon-envelope-open "></i> INFO@ISOFIX-MSK.RU</li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xl-4 col-lg-4">
                        <div class="header-offer-wrap-3 text-center">
                            <!-- <p>Free shipping worldwide for orders over $99 <a href="#">Learn More</a></p> -->
                        </div>
                    </div>
                    <div class="col-xl-4 col-lg-5">
                        <div class="header-top-right">
                            <div class="social-hm4-wrap">
                                <span></span>
<!--                                 <div class="social-style-1 social-style-1-white">
                                    <a href="https://www.youtube.com/channel/UCk01i_mNnY9ap77iQIonltQ" target="_blank"><i class="fa fa-youtube-play" aria-hidden="true"></i></a>
                                    <a href="#" target="_blank"><i class="fa fa-vk" aria-hidden="true"></i></a>
                                    <a href="#" target="_blank"><i class="fa fa-telegram" aria-hidden="true"></i></a>
                                    <a href="#" target="_blank"><i class="fa fa-odnoklassniki-square" aria-hidden="true"></i></a>
                                    <a href="#" target="_blank"><i class="fa fa-whatsapp" aria-hidden="true"></i></a>
                                </div> -->
                            </div>
                            <div class="hm4-currency-language-wrap same-style-wrap">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="header-bottom">
            <div class="container-fluid">
                <div class="border-bottom-6">
                    <div class="row align-items-center">
                        <div class="col-xl-3 col-lg-2">
                            <div class="logo">
                                <a href="{% url 'shop:home' %}"><img src="/static/shop/images/logo/logo_isofix.png"></a>
                            </div>
                        </div>
                        <div class="col-xl-7 col-lg-8">
                            <div class="main-menu main-menu-padding-1 main-menu-lh-3 main-menu-hm4 main-menu-center">
                                <nav>
                                    <ul>
                                        <li><a href="{% url 'shop:home' %}">ГЛАВНАЯ </a></li>
                                        <li><a href="{% url 'shop:shop_page' %}">ТОВАРЫ</a>
                                            <ul class="sub-menu-style">
                                               {% for category in categories %}
                                               {% if category.name|lower != 'услуги' %}
                                               <li>
                                                    <a href="{{category.get_absolute_url}}">{{category.name}} ISOFIX </a>
                                                </li>
                                                {% endif %}
                                               {% endfor %}
                                            </ul>
                                        </li>
                                        <li><a href="#">УСЛУГИ </a>
                                            <ul class="sub-menu-style">
                                                {% for service in get_services %}
                                                <li>
                                                    <a href="{{ service.get_absolute_url }}">{{ service.name }}</a>
                                                </li>
                                                {% endfor %}
                                            </ul>
                                        </li>
                                        <li><a href="#">ИНФОРМАЦИЯ </a>
                                            <ul class="sub-menu-style">
                                                <li><a href="{% url 'shop:contact' %}">Контакты </a></li>
                                                <li><a href="{% url 'shop:shipping_payment' %}">Доставка и оплата </a></li>
                                                <li><a href="{% url 'shop:about' %}">О Нас </a></li>
                                                <li><a href="{% url 'shop:policy' %}">Политика сайта </a></li>         
                                            </ul>
                                        </li>
                                        <li><a href="#">ОБЗОРЫ </a>
                                            <ul class="sub-menu-style">
                                                <li><a href="{% url 'shop:post_list' %}">Статьи </a></li>       
                                                <li><a href="{% url 'shop:video_list' %}">Видео </a></li>       
                                            </ul>
                                        </li>
                                        <!-- <li><a href="#">ДОСТАВКА И ОПЛАТА </a></li>
                                        <li><a href="#">КОНТАКТЫ </a></li>
                                        <li><a href="#">О НАС </a></li> -->
                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <div class="col-xl-2 col-lg-2">
                            <div class="header-action header-action-flex header-action-mrg-right">
                                <div class="header-cart-2">
                                    <a class="{% if not deactivate_mini_cart %}cart-active{% endif %} cart_info" href="{% url 'shop:cart_detail' %}">                                  
                                        <i class="icon-basket-loaded"></i>
                                        <img class="is_work mr-2 ml-1 {% if not is_install %}d-none{% endif %}" src="/static/shop/images/work.png">
                                        <span class="black">{{ cart|length }}</span><div class="format_currency">{{cart.get_total_price}}</div>
                                    </a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="header-small-device small-device-ptb-1 border-bottom-2">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-5">
                    <div class="mobile-logo">
                        <a href="{% url 'shop:home' %}">
                            <img alt="" src="/static/shop/images/logo/logo_isofix.png">
                        </a>
                    </div>
                </div>
                <div class="col-7">
                    <div class="header-action header-action-flex">
                        <div class="same-style-2 same-style-2-font-inc header-cart">
                            <a class="{% if not deactivate_mini_cart %}cart-active{% endif %} mini-cart cart_middle" href="{% url 'shop:cart_detail' %}">
                                <i class="icon-basket-loaded"></i>
                                <img height="20" class="is_work mr-0 ml-3 {% if not is_install %}d-none{% endif %}" src="/static/shop/images/work.png">
                                <span class="pro-count black">{{ cart|length }}</span>
                            </a>
                        </div>
                        <div class="same-style-2 main-menu-icon">
                            <a class="mobile-header-button-active" href="#"><i class="icon-menu"></i> </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

app/shop/templates/shop/includes/header_mobile.html
<div class="mobile-header-active mobile-header-wrapper-style">
    <div class="clickalbe-sidebar-wrap">
        <a class="sidebar-close"><i class="icon_close"></i></a>
        <div class="mobile-header-content-area">
            <div class="header-offer-wrap-3 mobile-header-padding-border-4">

                <div class="sidebar-wrapper sidebar-wrapper-mrg-right">
                    <div class="sidebar-widget mb-40">
                        <div class="sidebar-search">
                                <form class="sidebar-search-form" action="{% url 'shop:product_list' %}">
                                    <input type="text" name="search_query" placeholder="Что будем искать?">
                                    <button type="submit">
                                    <i class="icon-magnifier"></i>
                                    </button>
                                </form>
                        </div>
                    </div>
                </div>

            </div>
            <div class="mobile-menu-wrap mobile-header-padding-border-2">
                <!-- mobile menu start -->
                <nav>
                    <ul class="mobile-menu">
                        <li class="menu-item-has-children">
                            <a href="{% url 'shop:home' %}">Главная</a>
                        </li>
                        <li class="menu-item-has-children"><a href="#">Товары</a>
                            <ul class="dropdown">
                                {% for category in categories %}
                                {% if category.name|lower != 'услуги' %}
                                <li>
                                    <a href="{{category.get_absolute_url}}">{{category.name}} ISOFIX </a>
                                </li>
                                {% endif %}
                                {% endfor %}
                            </ul>
                        </li>
                        <li class="menu-item-has-children "><a href="#">Услуги</a>
                            <ul class="dropdown">
                                {% for service in get_services %}
                                <li><a href="{{ service.get_absolute_url }}">{{ service.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                        <li class="menu-item-has-children "><a href="#">Информация</a>
                            <ul class="dropdown">
                                <li><a href="{% url 'shop:contact' %}">Контакты </a></li>
                                <li><a href="{% url 'shop:shipping_payment' %}">Доставка и оплата </a></li>
                                <li><a href="{% url 'shop:about' %}">О Нас </a></li>
                                <li><a href="{% url 'shop:policy' %}">Политика сайта </a></li>    
                            </ul>
                        </li>
                        <li class="menu-item-has-children "><a href="#">Обзоры </a>
                            <ul class="dropdown">
                                <li><a href="{% url 'shop:post_list' %}">Статьи </a></li>       
                                <li><a href="{% url 'shop:video_list' %}">Видео </a></li>       
                            </ul>
                        </li>
                    </ul>
                </nav>
                <!-- mobile menu end -->
            </div>
            <div class="mobile-header-info-wrap mobile-header-padding-border-3">
                <!--                 <div class="single-mobile-header-info">
                    <a href="store-location.html"><i class="lastudioicon-pin-3-2"></i> Store Location </a>
                </div> -->
            </div>
            <div class="mobile-contact-info mobile-header-padding-border-4">
                <ul>
                    <li><i class="icon-phone "></i> <a class="hv" href="tel:+79651116527">+7-965-111-65-27</a></li>
                    <li><i class="icon-envelope-open "></i> INFO@ISOFIX-MSK.RU</li>
                    <li><i class="icon-home"></i>
                        <a class="hv pl-2" href="https://yandex.ru/maps/?rtext=~55.645283,37.403216">
                        г. Москва, Солнцево, ул.Щорса, д.8 стр.1 – автокомплекс “Buncar”
                        </a>
                    </li>
                </ul>
            </div>
            <div class="mobile-social-icon">
<!--                 <a class="bg-light text-dark" href="https://www.youtube.com/channel/UCk01i_mNnY9ap77iQIonltQ" target="_blank"><i class="fa fa-youtube-play" aria-hidden="true"></i></a>
                <a class="bg-light text-dark" href="#" target="_blank"><i class="fa fa-vk" aria-hidden="true"></i></a>
                <a class="bg-light text-dark" href="#" target="_blank"><i class="fa fa-telegram" aria-hidden="true"></i></a>
                <a class="bg-light text-dark" href="#" target="_blank"><i class="fa fa-odnoklassniki-square" aria-hidden="true"></i></a>
                <a class="bg-light text-dark" href="#" target="_blank"><i class="fa fa-whatsapp" aria-hidden="true"></i></a> -->
            </div>
        </div>
    </div>
</div>

app/shop/templates/shop/includes/modal.html
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="modal_quickView_close close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">x</span></button>
            </div>
            <div id="modal_body_q" class="modal-body">

            </div>
        </div>
    </div>
</div>
<!-- Modal end -->