app/shop/urls.py
from django.urls import path, include

from .views import view, shop, cart, order, blog, cdek, error, pmap

app_name = 'shop'

handler404 = 'shop.views.error.page_not_found'
handler400 = 'shop.views.error.bad_request'
handler403 = 'shop.views.error.permission_denied'

urlpatterns = [
    path('', view.home, name='home'),
    path('make/map/', pmap.make_map, name='make_map'),
    path('about-us/', view.about, name='about'),
    path(u'доставка-и-оплата/', view.shipping_payment, name='shipping_payment'),
    path('pdd/', view.pdd, name='pdd'),
    path('video/', view.video_list, name='video_list'),
    path('policy/', view.policy, name='policy'),
    path('clear/session/', view.clear_session, name='clear_session'),
    path('contact/', include([
        path('', view.contact, name='contact'),
        path('form/', view.get_message_form, name='get_message_form'),
        path('<str:message>/', view.contact, name='contact'),
        path('send/massage/', view.contact_send_message, name='contact_send_message'),
    ])),
    path('shop/', shop.product_list, name='shop_page'),
    path('product/loop_id/', shop.loop_id, name='loop_id'),
    path('product/<slug:slug>/', shop.product_detail, name='product_detail'),
    # /product-category/{{brand}}/ - прописан жестко в product/list.html - 1 раз
    path(u'product-category/', include([
        path('аксессуары/', shop.product_list, name='product_list'),
        path('filter/', shop.product_filter, name='product_filter'),
        path('size/<int:size>/', shop.product_list_size, name='product_list_size'),
        path('sort/<str:sort_by>/', shop.product_sort_by, name='product_sort_by'),
        path('toggle/<str:view_style>/', shop.toggle_style, name='toggle_style'),
        path('<slug:category_slug>/', shop.product_list, name='product_list_by_category'),
        path('krepleniya-isofix/<slug:category_slug>/',
             shop.product_list, name='product_list_by_category'),
    ])),
    path('cart/', include([
        path('', cart.cart_detail, name='cart_detail'),
        path('remove/loop/marker/', cart.remove_loop_marker, name='remove_loop_marker'),
        path('json/', cart.cart_json, name='cart_json'),
        path('clear/', cart.cart_clear, name='cart_clear'),
        path('count/quantity/on/', cart.cart_count_quantity, name='cart_count_quantity'),
        path('add/<int:product_id>/', cart.cart_add, name='cart_add'),
        # /cart/remove/id - прописан жестко в JS
        path('remove/<int:product_id>/', cart.cart_remove, name='cart_remove'),
        # /cart/remove/loop/id - прописан жестко в JS
        path('remove/loop/<int:product_id>/', cart.cart_remove_loop, name='cart_remove_loop'),
        path('add/delivery/tax/', cart.add_delivery_tax, name='add_delivery_tax'),
        path('add/percent/', cart.add_percent, name='add_percent'),
        # del/sessionkeyloop/<int:product_id>/ - прописан жестко в JS
        path('del/sessionkeyloop/<int:product_id>/',
             cart.cart_loop_off, name='cart_loop_off'),
        path('set/marker/on/<int:product_id>/',
             cart.set_loop_marker_on, name='set_loop_marker_on'),
    ])),
    path('order/', include([
        path('create/', order.order_create, name='order_create'),
        path('created/', order.order_created, name='order_created'),
    ])),
    path('blog/', include([
        path('', blog.post_list, name='post_list'),
        path('<slug:post>/', blog.post_detail, name='post_detail'),
    ])),
    path('cdek/', include([
        path('tariffs/', cdek.tarifflist, name='tarifflist'),
        path('city/', cdek.get_city, name='get_city'),
        path('cities/', cdek.get_cities, name='get_cities'),
    ])),
    path('404/', error.page_not_found),
    path('400/', error.bad_request),
    path('403/', error.permission_denied),
    # re_path(r'^\w*', view.ret_index, name='ret_index'),
    # path('order/', include([])),
]

app/shop/views/blog.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage,\
                                  PageNotAnInteger
from django.views.generic import ListView
from django.views.decorators.cache import cache_page
from ..models import Post, Product
from .. import POSTS_DETAIL_CACHE_TIME
'''
https://isofix-msk.ru/blog/instrukciya-isofix/
https://isofix-msk.ru/blog/neskolko-kresel/
https://isofix-msk.ru/blog/podushka-bezopasnosti/
https://isofix-msk.ru/blog/avto-s-isofix/
https://isofix-msk.ru/blog/sertificati-kresel/
https://isofix-msk.ru/blog/isofix-standart/
'''

def post_list(request):
    object_list = Post.published.all()
    paginator = Paginator(object_list, 12)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request,
                 'shop/post/list.html',
                 {'page': posts,
                  'posts': posts})

# @cache_page(POSTS_DETAIL_CACHE_TIME)
def post_detail(request, post):
    post = get_object_or_404(Post, slug=post, status='published')
    return render(request,
                  'shop/post/detail.html',
            {
                  'post': post,
            })


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'shop/post/list.html'

app/shop/views/cart.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.http import HttpResponse
from decimal import Decimal

from .. import CART_SESSION_ID, NO_IMAGE_PATH, PERCENT
from ..models import Product
from ..cart import Cart
from ..ctx_proc import currency

import json
import logging


@require_POST
def cart_add(request, product_id):
    try:
        quantity = int(request.POST.get('quantity'))
        override = int(request.POST.get('override'))
        install = int(request.POST.get('price_install') or 0)
        loop = request.POST.get('loop')
    except Exception as e:
        print(e)
    else:
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)

        if quantity > 0:
            cart.add(product=product,
                     quantity=quantity,
                     override_quantity=override,
                     install=install,
                     loop=loop)

            if request.headers.get('X-Requested-With'):
                price = Decimal(cart.cart[str(product_id)]['price']) * quantity
                price_install = Decimal(cart.cart[str(product_id)]['price_install']) * quantity

                total_price = currency(request)['currency'] + str(price)
                total_price_install = currency(request)['currency'] + str(price_install)

                sub_total = currency(
                    request)['currency'] + str(cart.get_total_price())

                return HttpResponse(json.dumps({
                    'product_id': product_id,
                    'result': 'update',
                    'total_price': total_price,
                    'total_price_install': total_price_install,
                    'sub_total': sub_total,
                    'cart_length': len(cart),
                }))

    return redirect('shop:cart_detail')


@require_POST
def add_delivery_tax(request):
    delivery_tax = request.POST.get('delivery_tax')
    grand_total = 0
    cart = Cart(request)

    if delivery_tax:
        if int(delivery_tax) >= 0:
            grand_total = Decimal(cart.get_total_price()) + Decimal(delivery_tax)

            return HttpResponse(json.dumps({
                'grand_total': str(grand_total)
            }))

    return HttpResponse(json.dumps({'error': 'fail add delivery tax!'}))


@require_POST
def add_percent(request):
    percent = request.POST.get('percent')
    delivery_sum = request.POST.get('delivery_sum')
    grand_total = 0

    cart = Cart(request)

    if percent is not None:
        if int(percent) >= 0:
            percent = str(PERCENT) if int(percent) > 0 else '0'
            logging.debug('percent %s', percent)
            logging.debug('delivery_sum %s', delivery_sum)
            # percent = ((cart.get_total_price() + Decimal(delivery_sum)) /
            #            Decimal(100)) * Decimal(percent)
            # grand_total = (cart.get_total_price() + Decimal(delivery_sum)) + percent
            p = (cart.get_total_price() + Decimal(delivery_sum)) * Decimal(percent) / Decimal(100)
            grand_total = (cart.get_total_price() + Decimal(delivery_sum)) + p

            return HttpResponse(json.dumps({
                'grand_total': str(grand_total)
            }))

    return HttpResponse(json.dumps({'error': 'no add percent!'}))


@require_POST
def set_loop_marker_on(request, product_id):
    if request.session[CART_SESSION_ID].get(str(product_id)):
        request.session[CART_SESSION_ID][str(product_id)]['loop'] = 'on'
        request.session.modified = True
        return HttpResponse(f'set marker for product {product_id} OK')
    return HttpResponse(f'set marker for product {product_id} FAIL')


@require_POST
def remove_loop_marker(request):
    for item in request.session[CART_SESSION_ID].values():
        if 'loop' in item:
            item['loop'] = 'off'
    request.session.modified = True
    return HttpResponse('remove markers')


@require_POST
def cart_count_quantity(request):
    cart = Cart(request)
    quantity_on = 0
    for item in cart:
        if item.get('loop_quantity'):
            quantity_on += int(item['quantity'])

    return HttpResponse(json.dumps({'quantity_on': str(quantity_on)}))


@require_POST
def cart_loop_off(request, product_id):
    ''' удаляет отметку loop: on '''
    if request.session.get(CART_SESSION_ID):
        if request.session[CART_SESSION_ID][str(product_id)].get('loop'):
            del request.session[CART_SESSION_ID][str(product_id)]['loop']
            request.session.modified = True
            return HttpResponse(json.dumps({'loop_del': 'ok'}))

    return HttpResponse(json.dumps({'loop_del': 'no'}))


@require_POST
def cart_remove_loop(request, product_id):
    ''' колличество для установки петель якорного крепления '''
    logging.debug('cart_remove_loop %s', product_id)
    if request.session[CART_SESSION_ID].get(str(product_id)):
        qty = int(request.POST.get('quantity'))

        cart = Cart(request)
        # product only loop
        cart.session[CART_SESSION_ID][str(product_id)]['loop_quantity'] = 0
        cart.save()

        product = get_object_or_404(Product, attribute='loop')
        quantity = 0

        for item in cart.cart.values():
            if item.get('loop_quantity'):
                quantity += int(item['loop_quantity'])

        if quantity <= 0 and cart.session[CART_SESSION_ID].get(str(product.id)):
            del cart.session[CART_SESSION_ID][str(product.id)]
        else:
            if cart.session[CART_SESSION_ID].get(str(product.id)):
                cart.session[CART_SESSION_ID][str(product.id)]['quantity'] = quantity
        cart.save()

        return HttpResponse(json.dumps({"loop_quantity": quantity}))
    return HttpResponse(json.dumps({"loop_quantity": 'fail'}))


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)

    if (product.attribute == 'loop'):
        for item in cart.cart.values():
            if item.get('loop_quantity'):
                del item['loop_quantity']
        cart.save()

    if request.headers.get('X-Requested-With'):
        sub_total = currency(
            request)['currency'] + str(cart.get_total_price())
        return HttpResponse(json.dumps({
            'product_id': product_id,
            'result': 'remove',
            'sub_total': sub_total,
            'cart_length': len(cart),
        }))
    return redirect('shop:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'shop/cart/detail.html', {
        'cart': cart,
        'deactivate_mini_cart': True,
    })


def cart_json(request):
    cart = Cart(request)
    response_data = {}

    if len(cart) and request.headers.get('X-Requested-With'):
        for item in cart:
            product = item['product']
            image = NO_IMAGE_PATH
            if product.image_base:
                image = product.image_base.url
            response_data[str(product.id)] = {
                'name': product.name,
                'image': image,
                'price': currency(request)['currency'] + str(product.price),
                'total_price': currency(request)['currency'] + str(item['total_price']),
                'quantity': item['quantity'],
                'product_url': product.get_absolute_url(),
                'price_install': currency(request)['currency'] + str(item['price_install']),
                'attribute': product.attribute
            }
        response_data['sub_total'] = currency(
            request)['currency'] + str(cart.get_total_price())
        response_data['cart_length'] = str(len(cart))
        return HttpResponse(json.dumps(response_data))
    # else:
    #     return HttpResponse(json.dumps({'cart': 'empty'}))
    return redirect('shop:product_list')


def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect('shop:product_list')

app/shop/views/error.py
from django.shortcuts import render, redirect
from django.http import HttpResponse


def page_not_found(request, exception=None, template_name=''):
    return HttpResponse('404')


def bad_request(request, exception=None, template_name=''):
    return HttpResponse('400')


def permission_denied(request, exception=None, template_name=''):
    return HttpResponse('403')

app/shop/views/pmap.py
import os
import datetime
from django.views.decorators.http import require_POST
from django.http import HttpResponse
from urllib.parse import unquote
from pathlib import Path
from urllib.parse import unquote
from ..models import Category, Product


@require_POST
def make_map(request):
    cats = Category.objects.all()
    products = Product.objects.all()
    # host = request.META.get('HTTP_ORIGIN', 'https://isofix-msk.ru')
    host = 'https://isofix-msk.ru'
    base_dir = Path(__file__).resolve().parent.parent.parent
    file_path = os.path.join(base_dir, 'media', 'products', 'map.xml')
    dt = datetime.datetime.now()
    yml_catalog = '<yml_catalog date="' + dt.strftime('%Y-%m-%d %H:%M:%S') + '">\n'
    shop = '\t<shop>\n\t\t<name>ISOFIX-MSK</name>\n'

    categories = '\t\t<categories>\n'
    for cat in cats:
        categories += f'\t\t\t<category id="{cat.id}">\n\t\t\t\t<name>{cat.name}</name>\n\t\t\t</category>\n'
    categories += '\t\t</categories>\n'
    shop += categories

    offers = '\t\t<offers>\n'
    count = 0
    for p in products:
        offer = f'\t\t\t<offer id="{p.id}" productId="{p.id}" quantity="1">\n'
        offer += f'\t\t\t\t<categoryId>{p.category_id}</categoryId>\n'
        if p.image_base:
            offer += f'\t\t\t\t<picture>{host}{unquote(p.image_base.url)}</picture>\n'
        offer += f'\t\t\t\t<name>{p.name}</name>\n'
        offer += f'\t\t\t\t<productName>{p.name}</productName>\n'
        offer += f'\t\t\t\t<price>{p.price}</price>\n'
        offer += f'\t\t\t\t<url>{host}/product/{p.slug}/</url>\n'
        if p.brand_car:
            offer += f'\t\t\t\t<param code="pa_brand" name="Марка машины:">{p.brand_car}</param>\n'
        if p.year:
            offer += f'\t\t\t\t<param code="pa_god-vipuska" name="Год выпуска:">{p.year}</param>\n'
        if p.model_car:
            offer += f'\t\t\t\t<param code="pa_model" name="Модель машины:">{p.model_car}</param>\n'
        if p.seat_type:
            offer += f'\t\t\t\t<param code="pa_tip-sideniya" name="Тип сидения:">{p.seat_type}</param>\n'
        offer += f'\t\t\t\t<param code="article" name="Article">{p.item_number}</param>\n'
        # offer += '\t\t\t\t<dimensions>50/20/10</dimensions>\n'
        # offer += '\t\t\t\t<weight>1.5</weight>\n'
        # offer += '\t\t\t\t<vatRate>none</vatRate>\n'
        offer += '\t\t\t</offer>\n'
        offers += offer

    offers += '\t\t</offers>\n'
    shop += offers
    # offers
    shop += '\t</shop>\n'
    yml_catalog += shop
    yml_catalog += '</yml_catalog>'
    with open(file_path, mode='w', encoding='utf-8') as file:
        file.write(yml_catalog)
    return HttpResponse(file_path)

app/shop/templates/shop/cart/detail.html
{% extends 'shop/base.html' %}
{% load static %}
{% load helpers %}
{% block title %}Корзина{% endblock %}
{% block content %}

<div class="breadcrumb-area bg-gray">
    <div class="container">
        <div class="breadcrumb-content text-center">
            <ul>
                <li>
                    <a href="{% url 'shop:home' %}">Главная</a>
                </li>
                <li class="active">Корзина </li>
            </ul>
        </div>
    </div>
</div>
<style>
    @media only screen and (max-width: 768px) {
        #fadeshow {
            display: none;
        }
    }
</style>

<div class="cart-main-area pt-115 pb-120 overflow-hidden">
    <div class="container" id="cart-container">
        {% if cart|length %}
        <h3 id="scroll_to_cart_title" class="cart-page-title mb-4">Выбранные товары</h3>
        <!-- row-cols-lg-2 -->
        <div class="row row-cols-1">
          {% for item in cart %}
          {% with product=item.product %}
          <form action="" method="post" class="col mb-4 cart-detail-products"
            data-product-id="{{product.id}}"
            data-product-attr="{{product.attribute}}"
            data-marker-url="{% url 'shop:set_loop_marker_on' product.id %}"
            data-marker-loop="{{item.loop}}">

            {% csrf_token %}
            {% if request.session.cart|get_key:product.id %}
            <input type="text" name="override" value="1" hidden>
            <input type="text" name="quantity" value="1" hidden>
            {% else %}
            <input type="text" name="override" value="0" hidden>
            <input type="text" name="quantity" value="1" hidden>
            {% endif %}

            <div class="card mb-3 border-0">
              <div class="row no-gutters">
                <div class="col-md-3">
                  <a href="{{ product.get_absolute_url }}">
                    <img class="w-100" src="{% if product.image_base %}{{ product.image_base.url }}{% else %}{{ no_image }}{% endif %}" alt="">
                  </a>
                </div>
                <div class="col-md-9">
                  <div class="card-body">
                    <h4 class="card-title">
                        <a class="hv" href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                    </h4>
                    <ul class="list-group list-group-flush">
                        {% if product.attribute == 'loop' %}
                        {% for i in cart %}
                        {% with p=i.product %}

                            {% if i.loop_quantity > 0 %}
                            <li class="list-group-item font-weight-bold">
                                <span class="text-danger">Вместе с:</span>
                                <a class="hv" href="{{ p.get_absolute_url }}">{{p.name}}</a>
                            </li>
                            {% endif %}

                        {% endwith %}
                        {% endfor %}
                        {% endif %}
<!--                         <li class="list-group-item">За еденицу:
                            <span style="position: absolute; right: 0;">
                                 1 x <b class="format_currency">{{ item.price }}</b>
                            </span>
                        </li>
                        <li class="list-group-item">За все:
                            <span style="position: absolute; right: 0;" class="product-subtotal text-danger">
                                 {{ item.quantity }} x <b class="format_currency">{{ item.total_price }}</b>
                            </span>
                        </li> -->

                        <li class="list-group-item">Стоимость:
                            <span style="position: absolute; right: 0;" class="product-subtotal">
                                 {{ item.quantity }} x <b class="format_currency">{{ item.total_price }}</b>
                            </span>
                        </li>

                        {% if product.product_type == 'кронштейн' and product.attribute != 'loop' %}
                        <li class="item_install list-group-item bg-light mt-1">
                            <div class='spinner-border spinner-border-sm cart_detail_install_bracket_spiner d-none' role='status'>
                                <span class='sr-only'>Загрузка...</span>
                            </div>

                                <span class="font-weight-bold">Установка кронштейна </span>
                                <input 
                                type="checkbox" 
                                class="form-check-input d-loop cart_detail_install_bracket" 
                                name="price_install" value="1"
                                style="
                                    max-width: 110px;
                                    max-height: 40px;
                                    zoom: 0.4;
                                    cursor: pointer;
                                " {% if item.total_price_install > 0 %} checked {% endif %}>
                            <br>
                            <div class='spinner-border spinner-border-sm cart_detail_install_loop_spiner d-none' role='status'>
                                <span class='sr-only'>Загрузка...</span>
                            </div>

                                <span class="font-weight-bold">Петля для якорного крепления </span>
                                <input
                                id="add_anchor"
                                class="form-check-input cart_detail_install_loop"
                                type="checkbox" name="loop"
                                style="
                                    max-width: 80px;
                                    margin-left: -7px;
                                    max-height: 40px;
                                    zoom: 0.4;
                                    cursor: pointer;
                                " {% if request.session.cart|is_loop_install:product.id %} checked {% endif %}>
                        </li>
                        {% endif %}


                    </ul>
                    <div class="mt-20 d-none">
                        <div class="product-quantity pro-details-quality text-center mt-5">
                            <div class="cart-plus-minus">
                                <input class="cart-plus-minus-box" type="text" name="qtybutton" value="{{ item.quantity }}" disabled>
                            </div>
                        </div>

                        <div class="d-flex justify-content-center">
                            <div class="m-1">
                                <button type="submit" class="btn_update btn btn-dark btn-sm bg-black" data-update-url="{% url 'shop:cart_add' product.id %}">
                                    Обновить
                                </button>
                            </div>
                            <div class="spinner-border spinner-border-sm d-none spiner" role="status" aria-hidden="true"></div>
                            <div class="m-1">
                                <button type="submit" class="btn_remove btn btn-danger btn-sm" data-delete-url="{% url 'shop:cart_remove' product.id %}">
                                    Удалить
                                </button>
                            </div>
                        </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </form>
          {% endwith %}
          {% endfor %}


          {% if cart.get_products_install_total_price > 0 %}
          <h3 class="cart-page-title mb-4 ml-3">Товары на установку</h3>
          {% for item in cart %}
          {% with product=item.product %}

          {% if item.total_price_install > 0 and product.attribute != 'loop' and product.product_type != 'услуга' and product.product_type != 'рейка'%}
          <div class="col mb-4">
            <div class="card mb-3 border-0">
              <div class="row no-gutters">
                <div class="col-md-3">
                    <a href="{{ product.get_absolute_url }}">
                        <img class="w-100" src="{% if product.image_base %}{{ product.image_base.url }}{% else %}{{ no_image }}{% endif %}">
                    </a>
                </div>
                <div class="col-9">
                  <div class="card-body">
                    <!-- <h4 class="card-title"></h4> -->
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item font-weight-bold">
                            <span class="text-danger">Установка: </span>
                            <a class="hv" href="{{ product.get_absolute_url }}">
                                {{product.name}}
                            </a>
                        </li>
<!--                         <li class="list-group-item">За единицу:
                            <span style="position: absolute; right: 0;">
                                1 x <b class="format_currency">{{ item.price_install }}</b>
                            </span>
                        </li>
                        <li class="list-group-item">За все:
                            <span style="position: absolute; right: 0;" class="product-subtotal text-danger">
                                {{ item.quantity }} x <b class="format_currency">{{ item.total_price_install }}</b>
                            </span>
                        </li> -->

                        <li class="list-group-item">Стоимость:
                            <span style="position: absolute; right: 0;" class="product-subtotal">
                                {{ item.quantity }} x <b class="format_currency">{{ item.total_price_install }}</b>
                            </span>
                        </li>

                    </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% endif %}

          {% endwith %}
          {% endfor %}
          {% endif %}


        </div>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                <div class="row mt-2">
                    <div class="col-md-7">
                        <div class="cart-shiping-update-wrapper">
                            <div class="cart-shiping-update pt-0 mt-0">
                                <a href="{% url 'shop:product_list' %}">Каталог</a>
                                <a href="{% url 'shop:cart_clear' %}">Очистить</a>
                            </div>
                            <div class="cart-clear text-center">

                            </div>
                        </div>
                    </div>

                    <div class="col-md-5">
                        <div class="grand-totall">
                            <div class="title-wrap mb-50">
                                <h4 class="cart-bottom-title section-bg-gary-cart">Итого</h4>
                            </div>
                            <h4 id="grand_total" class="grand-totall-title GT">Подитог <span class="format_currency">{{ cart.get_total_price }}</span></h4>
                            <a href="{% url 'shop:order_create' %}">Оформить заказ</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% else %}
        <div class="text-center">
            <h3>Ваша корзина пуста</h3>
            <a class="btn btn-danger" href="{% url 'shop:product_list' %}">Перейти к покупкам</a>
        </div>

        {% endif %}
    </div>
</div>

{% endblock %}