app/shop/urls.py
from django.urls import path, include

from .views import view, shop, cart, order, blog, cdek, error, pmap

app_name = 'shop'

handler404 = 'shop.views.error.page_not_found'
handler400 = 'shop.views.error.bad_request'
handler403 = 'shop.views.error.permission_denied'

urlpatterns = [
    path('', view.home, name='home'),
    path('make/map/', pmap.make_map, name='make_map'),
    path('about-us/', view.about, name='about'),
    path(u'доставка-и-оплата/', view.shipping_payment, name='shipping_payment'),
    path('pdd/', view.pdd, name='pdd'),
    path('video/', view.video_list, name='video_list'),
    path('policy/', view.policy, name='policy'),
    path('clear/session/', view.clear_session, name='clear_session'),
    path('contact/', include([
        path('', view.contact, name='contact'),
        path('form/', view.get_message_form, name='get_message_form'),
        path('<str:message>/', view.contact, name='contact'),
        path('send/massage/', view.contact_send_message, name='contact_send_message'),
    ])),
    path('shop/', shop.product_list, name='shop_page'),
    path('product/loop_id/', shop.loop_id, name='loop_id'),
    path('product/<slug:slug>/', shop.product_detail, name='product_detail'),
    # /product-category/{{brand}}/ - прописан жестко в product/list.html - 1 раз
    path(u'product-category/', include([
        path('аксессуары/', shop.product_list, name='product_list'),
        path('filter/', shop.product_filter, name='product_filter'),
        path('size/<int:size>/', shop.product_list_size, name='product_list_size'),
        path('sort/<str:sort_by>/', shop.product_sort_by, name='product_sort_by'),
        path('toggle/<str:view_style>/', shop.toggle_style, name='toggle_style'),
        path('<slug:category_slug>/', shop.product_list, name='product_list_by_category'),
        path('krepleniya-isofix/<slug:category_slug>/',
             shop.product_list, name='product_list_by_category'),
    ])),
    path('cart/', include([
        path('', cart.cart_detail, name='cart_detail'),
        path('remove/loop/marker/', cart.remove_loop_marker, name='remove_loop_marker'),
        path('json/', cart.cart_json, name='cart_json'),
        path('clear/', cart.cart_clear, name='cart_clear'),
        path('count/quantity/on/', cart.cart_count_quantity, name='cart_count_quantity'),
        path('add/<int:product_id>/', cart.cart_add, name='cart_add'),
        # /cart/remove/id - прописан жестко в JS
        path('remove/<int:product_id>/', cart.cart_remove, name='cart_remove'),
        # /cart/remove/loop/id - прописан жестко в JS
        path('remove/loop/<int:product_id>/', cart.cart_remove_loop, name='cart_remove_loop'),
        path('add/delivery/tax/', cart.add_delivery_tax, name='add_delivery_tax'),
        path('add/percent/', cart.add_percent, name='add_percent'),
        # del/sessionkeyloop/<int:product_id>/ - прописан жестко в JS
        path('del/sessionkeyloop/<int:product_id>/',
             cart.cart_loop_off, name='cart_loop_off'),
        path('set/marker/on/<int:product_id>/',
             cart.set_loop_marker_on, name='set_loop_marker_on'),
    ])),
    path('order/', include([
        path('create/', order.order_create, name='order_create'),
        path('created/', order.order_created, name='order_created'),
    ])),
    path('blog/', include([
        path('', blog.post_list, name='post_list'),
        path('<slug:post>/', blog.post_detail, name='post_detail'),
    ])),
    path('cdek/', include([
        path('tariffs/', cdek.tarifflist, name='tarifflist'),
        path('city/', cdek.get_city, name='get_city'),
        path('cities/', cdek.get_cities, name='get_cities'),
    ])),
    path('404/', error.page_not_found),
    path('400/', error.bad_request),
    path('403/', error.permission_denied),
    # re_path(r'^\w*', view.ret_index, name='ret_index'),
    # path('order/', include([])),
]

app/shop/views/blog.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage,\
                                  PageNotAnInteger
from django.views.generic import ListView
from django.views.decorators.cache import cache_page
from ..models import Post, Product
from .. import POSTS_DETAIL_CACHE_TIME
'''
https://isofix-msk.ru/blog/instrukciya-isofix/
https://isofix-msk.ru/blog/neskolko-kresel/
https://isofix-msk.ru/blog/podushka-bezopasnosti/
https://isofix-msk.ru/blog/avto-s-isofix/
https://isofix-msk.ru/blog/sertificati-kresel/
https://isofix-msk.ru/blog/isofix-standart/
'''

def post_list(request):
    object_list = Post.published.all()
    paginator = Paginator(object_list, 12)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request,
                 'shop/post/list.html',
                 {'page': posts,
                  'posts': posts})

# @cache_page(POSTS_DETAIL_CACHE_TIME)
def post_detail(request, post):
    post = get_object_or_404(Post, slug=post, status='published')
    return render(request,
                  'shop/post/detail.html',
            {
                  'post': post,
            })


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'shop/post/list.html'

app/shop/views/cart.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.http import HttpResponse
from decimal import Decimal

from .. import CART_SESSION_ID, NO_IMAGE_PATH, PERCENT
from ..models import Product
from ..cart import Cart
from ..ctx_proc import currency

import json
import logging


@require_POST
def cart_add(request, product_id):
    try:
        quantity = int(request.POST.get('quantity'))
        override = int(request.POST.get('override'))
        install = int(request.POST.get('price_install') or 0)
        loop = request.POST.get('loop')
    except Exception as e:
        print(e)
    else:
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)

        if quantity > 0:
            cart.add(product=product,
                     quantity=quantity,
                     override_quantity=override,
                     install=install,
                     loop=loop)

            if request.headers.get('X-Requested-With'):
                price = Decimal(cart.cart[str(product_id)]['price']) * quantity
                price_install = Decimal(cart.cart[str(product_id)]['price_install']) * quantity

                total_price = currency(request)['currency'] + str(price)
                total_price_install = currency(request)['currency'] + str(price_install)

                sub_total = currency(
                    request)['currency'] + str(cart.get_total_price())

                return HttpResponse(json.dumps({
                    'product_id': product_id,
                    'result': 'update',
                    'total_price': total_price,
                    'total_price_install': total_price_install,
                    'sub_total': sub_total,
                    'cart_length': len(cart),
                }))

    return redirect('shop:cart_detail')


@require_POST
def add_delivery_tax(request):
    delivery_tax = request.POST.get('delivery_tax')
    grand_total = 0
    cart = Cart(request)

    if delivery_tax:
        if int(delivery_tax) >= 0:
            grand_total = Decimal(cart.get_total_price()) + Decimal(delivery_tax)

            return HttpResponse(json.dumps({
                'grand_total': str(grand_total)
            }))

    return HttpResponse(json.dumps({'error': 'fail add delivery tax!'}))


@require_POST
def add_percent(request):
    percent = request.POST.get('percent')
    delivery_sum = request.POST.get('delivery_sum')
    grand_total = 0

    cart = Cart(request)

    if percent is not None:
        if int(percent) >= 0:
            percent = str(PERCENT) if int(percent) > 0 else '0'
            logging.debug('percent %s', percent)
            logging.debug('delivery_sum %s', delivery_sum)
            # percent = ((cart.get_total_price() + Decimal(delivery_sum)) /
            #            Decimal(100)) * Decimal(percent)
            # grand_total = (cart.get_total_price() + Decimal(delivery_sum)) + percent
            p = (cart.get_total_price() + Decimal(delivery_sum)) * Decimal(percent) / Decimal(100)
            grand_total = (cart.get_total_price() + Decimal(delivery_sum)) + p

            return HttpResponse(json.dumps({
                'grand_total': str(grand_total)
            }))

    return HttpResponse(json.dumps({'error': 'no add percent!'}))


@require_POST
def set_loop_marker_on(request, product_id):
    if request.session[CART_SESSION_ID].get(str(product_id)):
        request.session[CART_SESSION_ID][str(product_id)]['loop'] = 'on'
        request.session.modified = True
        return HttpResponse(f'set marker for product {product_id} OK')
    return HttpResponse(f'set marker for product {product_id} FAIL')


@require_POST
def remove_loop_marker(request):
    for item in request.session[CART_SESSION_ID].values():
        if 'loop' in item:
            item['loop'] = 'off'
    request.session.modified = True
    return HttpResponse('remove markers')


@require_POST
def cart_count_quantity(request):
    cart = Cart(request)
    quantity_on = 0
    for item in cart:
        if item.get('loop_quantity'):
            quantity_on += int(item['quantity'])

    return HttpResponse(json.dumps({'quantity_on': str(quantity_on)}))


@require_POST
def cart_loop_off(request, product_id):
    ''' удаляет отметку loop: on '''
    if request.session.get(CART_SESSION_ID):
        if request.session[CART_SESSION_ID][str(product_id)].get('loop'):
            del request.session[CART_SESSION_ID][str(product_id)]['loop']
            request.session.modified = True
            return HttpResponse(json.dumps({'loop_del': 'ok'}))

    return HttpResponse(json.dumps({'loop_del': 'no'}))


@require_POST
def cart_remove_loop(request, product_id):
    ''' колличество для установки петель якорного крепления '''
    logging.debug('cart_remove_loop %s', product_id)
    if request.session[CART_SESSION_ID].get(str(product_id)):
        qty = int(request.POST.get('quantity'))

        cart = Cart(request)
        # product only loop
        cart.session[CART_SESSION_ID][str(product_id)]['loop_quantity'] = 0
        cart.save()

        product = get_object_or_404(Product, attribute='loop')
        quantity = 0

        for item in cart.cart.values():
            if item.get('loop_quantity'):
                quantity += int(item['loop_quantity'])

        if quantity <= 0 and cart.session[CART_SESSION_ID].get(str(product.id)):
            del cart.session[CART_SESSION_ID][str(product.id)]
        else:
            if cart.session[CART_SESSION_ID].get(str(product.id)):
                cart.session[CART_SESSION_ID][str(product.id)]['quantity'] = quantity
        cart.save()

        return HttpResponse(json.dumps({"loop_quantity": quantity}))
    return HttpResponse(json.dumps({"loop_quantity": 'fail'}))


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)

    if (product.attribute == 'loop'):
        for item in cart.cart.values():
            if item.get('loop_quantity'):
                del item['loop_quantity']
        cart.save()

    if request.headers.get('X-Requested-With'):
        sub_total = currency(
            request)['currency'] + str(cart.get_total_price())
        return HttpResponse(json.dumps({
            'product_id': product_id,
            'result': 'remove',
            'sub_total': sub_total,
            'cart_length': len(cart),
        }))
    return redirect('shop:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'shop/cart/detail.html', {
        'cart': cart,
        'deactivate_mini_cart': True,
    })


def cart_json(request):
    cart = Cart(request)
    response_data = {}

    if len(cart) and request.headers.get('X-Requested-With'):
        for item in cart:
            product = item['product']
            image = NO_IMAGE_PATH
            if product.image_base:
                image = product.image_base.url
            response_data[str(product.id)] = {
                'name': product.name,
                'image': image,
                'price': currency(request)['currency'] + str(product.price),
                'total_price': currency(request)['currency'] + str(item['total_price']),
                'quantity': item['quantity'],
                'product_url': product.get_absolute_url(),
                'price_install': currency(request)['currency'] + str(item['price_install']),
                'attribute': product.attribute
            }
        response_data['sub_total'] = currency(
            request)['currency'] + str(cart.get_total_price())
        response_data['cart_length'] = str(len(cart))
        return HttpResponse(json.dumps(response_data))
    # else:
    #     return HttpResponse(json.dumps({'cart': 'empty'}))
    return redirect('shop:product_list')


def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect('shop:product_list')

app/shop/views/error.py
from django.shortcuts import render, redirect
from django.http import HttpResponse


def page_not_found(request, exception=None, template_name=''):
    return HttpResponse('404')


def bad_request(request, exception=None, template_name=''):
    return HttpResponse('400')


def permission_denied(request, exception=None, template_name=''):
    return HttpResponse('403')

app/shop/views/pmap.py
import os
import datetime
from django.views.decorators.http import require_POST
from django.http import HttpResponse
from urllib.parse import unquote
from pathlib import Path
from urllib.parse import unquote
from ..models import Category, Product


@require_POST
def make_map(request):
    cats = Category.objects.all()
    products = Product.objects.all()
    # host = request.META.get('HTTP_ORIGIN', 'https://isofix-msk.ru')
    host = 'https://isofix-msk.ru'
    base_dir = Path(__file__).resolve().parent.parent.parent
    file_path = os.path.join(base_dir, 'media', 'products', 'map.xml')
    dt = datetime.datetime.now()
    yml_catalog = '<yml_catalog date="' + dt.strftime('%Y-%m-%d %H:%M:%S') + '">\n'
    shop = '\t<shop>\n\t\t<name>ISOFIX-MSK</name>\n'

    categories = '\t\t<categories>\n'
    for cat in cats:
        categories += f'\t\t\t<category id="{cat.id}">\n\t\t\t\t<name>{cat.name}</name>\n\t\t\t</category>\n'
    categories += '\t\t</categories>\n'
    shop += categories

    offers = '\t\t<offers>\n'
    count = 0
    for p in products:
        offer = f'\t\t\t<offer id="{p.id}" productId="{p.id}" quantity="1">\n'
        offer += f'\t\t\t\t<categoryId>{p.category_id}</categoryId>\n'
        if p.image_base:
            offer += f'\t\t\t\t<picture>{host}{unquote(p.image_base.url)}</picture>\n'
        offer += f'\t\t\t\t<name>{p.name}</name>\n'
        offer += f'\t\t\t\t<productName>{p.name}</productName>\n'
        offer += f'\t\t\t\t<price>{p.price}</price>\n'
        offer += f'\t\t\t\t<url>{host}/product/{p.slug}/</url>\n'
        if p.brand_car:
            offer += f'\t\t\t\t<param code="pa_brand" name="Марка машины:">{p.brand_car}</param>\n'
        if p.year:
            offer += f'\t\t\t\t<param code="pa_god-vipuska" name="Год выпуска:">{p.year}</param>\n'
        if p.model_car:
            offer += f'\t\t\t\t<param code="pa_model" name="Модель машины:">{p.model_car}</param>\n'
        if p.seat_type:
            offer += f'\t\t\t\t<param code="pa_tip-sideniya" name="Тип сидения:">{p.seat_type}</param>\n'
        offer += f'\t\t\t\t<param code="article" name="Article">{p.item_number}</param>\n'
        # offer += '\t\t\t\t<dimensions>50/20/10</dimensions>\n'
        # offer += '\t\t\t\t<weight>1.5</weight>\n'
        # offer += '\t\t\t\t<vatRate>none</vatRate>\n'
        offer += '\t\t\t</offer>\n'
        offers += offer

    offers += '\t\t</offers>\n'
    shop += offers
    # offers
    shop += '\t</shop>\n'
    yml_catalog += shop
    yml_catalog += '</yml_catalog>'
    with open(file_path, mode='w', encoding='utf-8') as file:
        file.write(yml_catalog)
    return HttpResponse(file_path)

app/shop/templates/shop/base.html
<!doctype html>
<html class="no-js" lang="ru-RU">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="keywords" content="{% block keywords %}{% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon -->
    <!-- <link rel="shortcut icon" type="image/x-icon" href="/static/shop/assets/images/favicon.png"> -->
    <link rel="apple-touch-icon" sizes="57x57" href="/static/shop/images/fav/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/static/shop/images/fav/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/static/shop/images/fav/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/static/shop/images/fav/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/static/shop/images/fav/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/static/shop/images/fav/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/static/shop/images/fav/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/static/shop/images/fav/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/static/shop/images/fav/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/static/shop/images/fav/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/shop/images/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/static/shop/images/fav/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/shop/images/fav/favicon-16x16.png">
    <link rel="manifest" href="/static/shop/images/fav/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/static/shop/images/fav/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    <!-- All CSS is here
    ============================================ -->
    <!-- <link rel="stylesheet" href="/static/shop/assets/css/vendor/bootstrap.min.css">
    <link rel="stylesheet" href="/static/shop/assets/css/vendor/signericafat.css">
    <link rel="stylesheet" href="/static/shop/assets/css/vendor/cerebrisans.css">
    <link rel="stylesheet" href="/static/shop/assets/css/vendor/simple-line-icons.css">
    <link rel="stylesheet" href="/static/shop/assets/css/vendor/elegant.css">
    <link rel="stylesheet" href="/static/shop/assets/css/vendor/linear-icon.css">
    <link rel="stylesheet" href="/static/shop/assets/css/plugins/nice-select.css">
    <link rel="stylesheet" href="/static/shop/assets/css/plugins/easyzoom.css">
    <link rel="stylesheet" href="/static/shop/assets/css/plugins/slick.css">
    <link rel="stylesheet" href="/static/shop/assets/css/plugins/animate.css">
    <link rel="stylesheet" href="/static/shop/assets/css/plugins/magnific-popup.css">
    <link rel="stylesheet" href="/static/shop/assets/css/plugins/jquery-ui.css"> -->
    <link rel="stylesheet" href="/static/shop/assets/css/font-awesome-4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/static/shop/assets/css/vendor/vendor.min.css">
    <link rel="stylesheet" href="/static/shop/assets/css/plugins/plugins.min.css">
    <link rel="stylesheet" href="/static/shop/assets/js/inttel/css/intlTelInput.min.css">
    <link href="https://cdn.jsdelivr.net/npm/suggestions-jquery@21.12.0/dist/css/suggestions.min.css" rel="stylesheet" />
    <!-- <link rel="stylesheet" href="/static/shop/assets/css/plugins/jquery-ui.css"> -->
    <link rel="stylesheet" href="/static/shop/assets/css/style.css">
    <link rel="stylesheet" href="/static/shop/assets/css/main.css">
    
<!-- Yandex.Metrika counter by Yandex Metrica Plugin -->
<!-- <script type="text/javascript" >
    (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
        m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
    (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

    ym(53499001, "init", {
        id:53499001,
        clickmap:true,
        trackLinks:true,
        accurateTrackBounce:false,
        webvisor:true,
            });
</script>
<noscript>
    <div><img src="https://mc.yandex.ru/watch/53499001" style="position:absolute; left:-9999px;" alt="" /></div>
</noscript> -->
<!-- /Yandex.Metrika counter -->
</head>

<body>
    <div class="main-wrapper">
        {% include 'shop/includes/header.html' %}
        <!-- mobile header start -->
        {% include 'shop/includes/header_mobile.html' %}
        <!-- mini cart start -->
        {% include 'shop/includes/mini_cart.html' %}
        {% block content %}{% endblock %}
        {% include 'shop/includes/footer.html' %}
        <!-- Modal -->
        {% include 'shop/includes/modal.html' %}
        <!-- Modal end -->
    </div>

<!--     <script type="text/javascript" >
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter53499001 = new Ya.Metrika({
                    id:53499001,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true,
                    webvisor:true,
                    ecommerce:"dataLayer"
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
        })(document, window, "yandex_metrika_callbacks");
    </script>
    <noscript><div><img src="https://mc.yandex.ru/watch/53499001" style="position:absolute; left:-9999px;" alt="" /></div></noscript> -->
    
<!--     <script type="text/javascript">
        (function() {
            var s = document.createElement("script"); 
            s.type = "text/javascript"; 
            s.async = true; 
            s.src = "https://leadball.ru/whats/float.php?id=yVpTzNxfVwCsCOu8BzIb"; 
            var wyVpTzN = document.getElementsByTagName("script")[0]; 
            wyVpTzN.parentNode.insertBefore(s, wyVpTzN); } 
        )();
    </script> -->
    <!-- All JS is here
============================================ -->
    <!-- <script src="/static/shop/assets/js/vendor/modernizr-3.6.0.min.js"></script> -->
    <script src="/static/shop/assets/js/vendor/jquery-3.5.1.min.js"></script>
    <!-- <script src="/static/shop/assets/js/vendor/jquery-migrate-3.3.0.min.js"></script> -->
    <script src="/static/shop/assets/js/vendor/bootstrap.bundle.min.js"></script>
    <script src="/static/shop/assets/js/plugins/slick.js"></script>
    <!-- <script src="/static/shop/assets/js/plugins/jquery.syotimer.min.js"></script> -->
    <!-- <script src="/static/shop/assets/js/plugins/jquery.instagramfeed.min.js"></script> -->
    <script src="/static/shop/assets/js/plugins/jquery.nice-select.min.js"></script>
    <script src="/static/shop/assets/js/plugins/wow.js"></script>
    <script src="/static/shop/assets/js/plugins/jquery-ui-touch-punch.js"></script>
    <script src="/static/shop/assets/js/plugins/jquery-ui.js"></script>
    <script src="/static/shop/assets/js/plugins/magnific-popup.js"></script>
    <script src="/static/shop/assets/js/plugins/sticky-sidebar.js"></script>
    <script src="/static/shop/assets/js/plugins/sticky-sidebar.js"></script>
    <!-- <script src="/static/shop/assets/js/plugins/easyzoom.js"></script> -->
    <script src="/static/shop/assets/js/plugins/scrollup.js"></script>
    <script src="/static/shop/assets/js/plugins/jquery.mask.min.js"></script>
    <script src="/static/shop/assets/js/inttel/js/intlTelInput-jquery.min.js"></script>

    <!-- <script src="/static/shop/assets/js/plugins/ajax-mail.js"></script> -->
    <!-- Use the minified version files listed below for better performance and remove the files listed above  
<script src="/static/shop/assets/js/vendor/vendor.min.js"></script>
<script src="/static/shop/assets/js/plugins/plugins.min.js"></script>  -->
    
    <!-- Main JS -->
    <script>
    var CSRF_TOKEN                  = '{% csrf_token %}';
    var PRODUCT_LIST_URL            = "{% url 'shop:product_list' %}"
    var CART_INFO_JSON_URL          = "{% url 'shop:cart_json' %}"
    var FILTER_URL                  = "{% url 'shop:product_filter' %}"
    var NO_IMAGE_URL                = "{{ no_image }}"
    var CURRENCY                    = "{{ currency }}"
    var CDEK_CITY_URL               = "{% url 'shop:get_city' %}"
    var CDEK_CITIES_URL             = "{% url 'shop:get_cities' %}"
    var CDEK_TARIFFLIST_URL         = "{% url 'shop:tarifflist' %}"
    var CART_ADD_DELIVERY_TAX_URL   = "{% url 'shop:add_delivery_tax' %}"
    var CART_ADD_PERCENT_URL        = "{% url 'shop:add_percent' %}"
    // var DEL_GRAND_TOTAL_SESSION_URL = ""
    var GET_LOOP_ID_URL             = "{% url 'shop:loop_id' %}"
    var CART_COUNT_QUANTITY_URL     = "{% url 'shop:cart_count_quantity' %}"
    var CART_REMOVE_LOOP_MARKER_URL = "{% url 'shop:remove_loop_marker' %}"
    var CART_DETAIL_URL             = "{% url 'shop:cart_detail' %}"
    var log = false

    if (window.innerWidth < 500 && document.getElementById("fimg")) {
        $(".slider-area").css({
            "overflow-x": "hidden", 
        })
        $("#fimg").css({
            "margin": "0 -100px 0 0",
        })
    }
    </script>

    {% block orderjs %}{% endblock %}
    {% block productjs %}{% endblock %}
    {% block paymaentjs %}{% endblock %}
    {% block contactjs %}{% endblock %}
    <script src="/static/shop/assets/js/main.js"></script>
</body>

</html>